name: PR Checks

on: pull_request

jobs:
  pr-checks:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    continue-on-error: true

    steps:
      - name: Clone the Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint
        # Intentionally only on Linux because output will be the same on all 
        # platforms and Linux is the least expensive.
        if: (success() || failure()) && matrix.os == 'ubuntu-latest'
        run: deno lint

      - name: Check Formatting
        # Intentionally only on Linux because output will be the same on all 
        # platforms and Linux is the least expensive.
        if: (success() || failure()) && matrix.os == 'ubuntu-latest'
        run: deno fmt --check

      - name: Test
        run: deno test -A --allow-none
      
      - name: Test Readme
        if: (success() || failure()) && matrix.os == 'ubuntu-latest'
        run: deno task test-readme
